version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop
    volumes:
      - namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop
    volumes:
      - datanode:/hadoop/dfs/data

  hive-metastore:
    image: bde2020/hive-metastore-postgresql:2.3.0
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    networks:
      - hadoop
    ports:
      - "5432:5432"

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    depends_on:
      - namenode
      - datanode
      - hive-metastore
    environment:
      - HIVE_METASTORE_HOST=hive-metastore
    ports:
      - "10000:10000"
    networks:
      - hadoop

volumes:
  namenode:
  datanode:

networks:
  hadoop:

