ors:
  engine:
    profile_default:
      build:
        source_file: new-york-latest.osm.pbf
    profiles:
      driving-car:
        enabled: true

  storage:
    location: "./graphs"
    osm_file: "./new-york-latest.osm.pbf"  # Ensure the correct file path.
    elevation_cache_path: "./elevation_cache"
    prepare:
      threads: 4
      min_network_size: 200
      min_one_way_network_size: 200
server:
  port: 8082
  error:
    whitelabel:
      enabled: false

#  ##### ORS engine settings #####
  engine:
    init_threads: 1
    preparation_mode: false
    graphs_data_access: RAM_STORE
    elevation:
      preprocessed: false
      data_access: MMAP
      cache_clear: false
      provider: multi
      cache_path: elevation_cache
    profile_default:
      enabled: false
      graph_path: graphs
      build:
        source_file:
        elevation: true
        elevation_smoothing: false
        encoder_flags_size: 8
        instructions: true
        optimize: false
        traffic: false
        maximum_speed_lower_bound: 80
        location_index_resolution: 500
        location_index_search_iterations: 4
        interpolate_bridges_and_tunnels: true
        preparation:
          min_network_size: 200
          methods:
            lm:
              enabled: true
              threads: 1
              weightings: recommended,shortest
              landmarks: 16
      service:
        maximum_distance: 100000
        maximum_distance_dynamic_weights: 100000
        maximum_distance_avoid_areas: 100000
        maximum_waypoints: 50
        maximum_snapping_radius: 400
        maximum_distance_alternative_routes: 100000
        maximum_distance_round_trip_routes: 100000
        maximum_visited_nodes: 1000000
        force_turn_costs: false
        allow_custom_models: true
        execution:
          methods:
            lm:
              active_landmarks: 8
